# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Use static linkage for frameworks
use_frameworks! :linkage => :static

target 'DripOutApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'DripOutAppTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # Firebase pods with modular headers
  pod 'Firebase'
  pod 'FirebaseCoreInternal'
  pod 'GoogleUtilities'
  pod 'FirebaseCore'
  pod 'FirebaseStorage'
  pod 'FirebaseAppCheckInterop' 
  pod 'FirebaseAuthInterop'
  pod 'FirebaseCoreExtension'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix Xcode 14 warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = "NO"
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = "NO"
        config.build_settings['GCC_WARN_UNDECLARED_SELECTOR'] = "NO"
      end
    end
    
    # Fix for PhaseScriptExecution issues (React Native Reanimated)
    installer.pods_project.targets.each do |target|
      if target.name == 'RNReanimated'
        phase = target.shell_script_build_phases.find { |ph| ph.name == '[CP-User] Generate Specs' }
        if phase
          phase.execution_position = :before_compile
        end
      end
    end

    # Allow non-modular includes in framework modules (GitHub issue fix)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = "YES"
    end
  end
end